name: Setup PHP Action

on: [push]

jobs:
  build:
    runs-on: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shanmuga1980/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, json
        ini-values: post_max_size=256M, max_execution_time=180, date.timezone=America/New_York, extension = php_mysqli, zend_extension = php_json
        coverage: xdebug2   
        tools: composer:v2
