name: Setup PHP Action

on: 
  push:
    branches:
      - main
      - node.js
  pull_request:
    branches:
      - main
      - node.js
  page_build:
  release:
    types:
      - created
      - deleted
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:            
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{matrix.language}}
        
    - name: Autobuild CodeQl
      uses: github/codeql-action/autobuild@v1
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
