name: docker
on: 

  push:
    branches:
      - main
      - node.js
      
  pull_request:
    branches:
      - main
      - node.js
      
  page_build:
  release:
    types:
      - created
      - deleted
      
  schedule:
    - cron:  '30 5,17 * * *'
jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'ubuntu-18.04', 'windows-latest', 'windows-2016', 'macos-latest']
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: run
      run: |
        $ cat ~/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 | docker login https://docker.pkg.github.com -u shanmuga1980 --password-stdin
        sudo docker build -t php/login-signup/create-db .
        sudo docker images
        sudo docker run -p 80:80 php/login-signup/create-db
        RUN echo hello \
        world

