name: Create Composer.json
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix: 
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{matrix.os}}
    env:
      interactive_mode: on
    steps:
      - uses: actions/checkout@v2
      - name: Create composer.json
        run:  php composer.phar init
