name: Setup PHP Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shanmuga1980/setup-php@v2
        with:
          php-version: '8.0.7'
          extensions: mysqli, exif, Xdebug
          ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M, date.timezone=America/New_York
          coverage: xdebug2
          tools: composer:v2
