name: Setup PHP Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.11.0
      with:
        php-version: '8.0'
      env:
        fail-fast: true
