name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'ubuntu-18.04', 'windows-latest', 'windows-2016', 'macos-latest']
      
    steps:
    - uses: actions/checkout@v2

    - name: One
      run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - name: Two
      run: php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - name: Three
      run: php composer-setup.php
    - name: Four
      run: php -r "unlink('composer-setup.php');"
