name: Setup PHP Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4.20'
          extensions: mysqli, redif, exif
          ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M
          coverage: xdebug2
          tools: composer:v2
          command: gh repo clone shivammathur/setup-php

