name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Composer
      uses: actions/checkout@v2
    - name: Install PHP
      uses: php-actions/composer@v6
      with:
        php_version: 8.0
        php_extensions: mysqli redis exif
        version: 2
    - name: Run Composer
      uses: php composer.phar
