name: php

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: 7.4
        php_extensions: mysqli
        version: 8
