name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependecies
      uses: php-actions/composer@v6
      with:
        php_version: 8.0
        php_extensions: mysqli redis exif
        version: 2
    
