name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Composer.phar
      uses: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      uses: php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      uses: php composer-setup.php
      uses: php -r "unlink('composer-setup.php');"
